version: "3"

services:
  mysql:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    read_only: true
    tmpfs:
      - /var/run/mysqld
      - /tmp
      - /var/lib/mysql
    security_opt:
      - no-new-privileges:true
  db-test:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    read_only: true
    tmpfs:
      - /var/run/mysqld
      - /tmp
      - /var/lib/mysql